### ISSUE TITLE
Version 1.1.0 does not like Firefox

### ISSUE THREAD

**Issue by MythicalRollers** [patrickporto/avqol#11]
## Describe the bug
When logging into Foundry via Firefox and A/V QoL is enabled, the world freezes.  Only able to get console errors if you have console up before logging into Foundry.  Trying after the fact is futile.  If using Chrome, everything is happy. If you disable A/V QoL and log in with Firefox after doing so, everything is happy.

## To Reproduce
1. Open Chrome
2. Browse to your world
3. enable only the below modules
4. log out
5. close Chrome
6. Open Firefox
7. Open console
8. Browse to your world
9. log in
10. See error

## Expected behavior
I expected my world to log in without freezing. 

## Screenshots
N/A

## Environment (please complete the following information):
 - Foundry VTT: 10.291
 - DnD5e: 2.1.5
 - Browser: Firefox 110.0.1
 - A/V QoL: 1.1.0
 - LiveKit: 0.5.19
 - Camera Dock: 0.9.1
 - libWrapper: 1.12.12.0

## Additional context ERROR:
Uncaught (in promise) TypeError: setting getter-only property "message"
[Detected 2 packages: lib-wrapper, avqol]
    onError foundry.js:746
    call_wrapped libWrapper-wrapper.js:507
    <anonymous> listeners.js:135
    onError#0 libWrapper-wrapper.js:187
    render foundry.js:5069
    promise callback*render foundry.js:5067
    render foundry.js:69700
    Dn camera-view.ts:35
    <anonymous> camera-view.ts:67
    #call foundry.js:724
    callAll foundry.js:681
    _render foundry.js:5153
    _render foundry.js:69707
    render foundry.js:5067
    render foundry.js:69700
    initializeUI foundry.js:8072
    setupGame foundry.js:7931
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
[foundry.js:746:43](https://rime.mythicalrollers.com/scripts/foundry.js)
Uncaught (in promise) TypeError: setting getter-only property "message"
[Detected 1 package: lib-wrapper]
    onError foundry.js:746
    call_wrapped libWrapper-wrapper.js:507
    <anonymous> listeners.js:135
    onError#0 libWrapper-wrapper.js:187
    render foundry.js:5069
    promise callback*render foundry.js:5067
    render foundry.js:69700
    initializeUI foundry.js:8072
    setupGame foundry.js:7931
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675
[foundry.js:746:43](https://rime.mythicalrollers.com/scripts/foundry.js)
    call_wrapped libWrapper-wrapper.js:511
    call_wrapped self-hosted:1521
    <anonymous> listeners.js:135
    wrapper self-hosted:1409
    onError#0 libWrapper-wrapper.js:187
    render foundry.js:5069
    (Async: promise callback)
    render foundry.js:5067
    render foundry.js:69700
    initializeUI foundry.js:8072
    setupGame foundry.js:7931
    InterpretGeneratorResume self-hosted:1822
    AsyncFunctionNext self-hosted:810
    (Async: async)
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    InterpretGeneratorResume self-hosted:1822
    AsyncFunctionNext self-hosted:810
    (Async: async)
    call_wrapped libWrapper-wrapper.js:507
    call_wrapped self-hosted:1521
    libWrapperInit libWrapper-api.js:803
    AsyncFunctionNext self-hosted:810
    (Async: async)
    libWrapperInit self-hosted:1409
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    AsyncFunctionNext self-hosted:810
    (Async: async)
    <anonymous> foundry.js:79675
TypeError: An error occurred while rendering Un 45. 'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
[Detected 2 packages: avqol, lib-wrapper]
    getData avsettings.ts:42
    _render foundry.js:5108
    _render foundry.js:5822
    render foundry.js:5067
    openSettings avqol.ts:23
    <anonymous> main.ts:56
    #call foundry.js:724
    callAll foundry.js:681
    setupGame foundry.js:7952
    _initializeGameView foundry.js:8999
    _initializeView foundry.js:8975
    initialize foundry.js:7825
    call_wrapped libWrapper-wrapper.js:507
    libWrapperInit libWrapper-api.js:803
    initialize#0 libWrapper-wrapper.js:187
    <anonymous> foundry.js:79693
    async* foundry.js:79675

**Comment by MythicalRollers** [comment]
This seems to be an issue with A/V QoL and Camera Dock in Firefox.  If I disable either of these modules, then my world works in Firefox.

**Comment by patrickporto** [comment]
I found a controversial issue about it: https://github.com/mozilla/standards-positions/issues/19
