### ISSUE TITLE
Add option to use VDO.Ninja as server

### ISSUE THREAD

**Issue by igorteuri** [patrickporto/avqol#14]
[vdo.ninja](https://vdo.ninja/) is free website that allows to share mic, camera and other things through internet. The use cutting edge Peer-to-Peer forwarding technology that offers privacy and ultra-low latency. 

Since the service can provide individual ID links to each person, it would be amazin to use it as a server to A/V client inside Foundry VTT.  

The best part, it's completely free!

This feature would be amazin for those who stream their games, because you would be able to get individual links for each person and insert them as browser sources in OBS Studio, while still are able to see the video chat inside Foundry`s UI.

**Comment by patrickporto** [comment]
@igorteuri I believe that adding a new server strays from the purpose of this module. If someday there is a module to support VDO.Ninja I will add support for it.
