### ISSUE TITLE
Feature request: aspect ratio of the video frame

### ISSUE THREAD

**Issue by 2old-4this** [patrickporto/avqol#2]
It's very useful to change the aspect ratio of the video frame, specially with vertical framing you are saving great amount of space. 

Also I suggest, if possible, the ability to crop - resize - move the captured video inside the video frame. 

Excellent work. Thanks allot for your effort

**Comment by patrickporto** [comment]
Hi @2old-4this 

Could you show me some examples?

**Comment by 2old-4this** [comment]
Yes, of course. By default, the framing has an aspect ratio of 4:3, which requires a lot of horizontal space. However, if we use a vertical aspect ratio of 3:4, for example, we can fit more players next to each other.
![AV-qol_9 16](https://user-images.githubusercontent.com/71936702/221961897-9ec3dfc2-e9cd-4356-aad6-2232395bda01.png)

**Comment by patrickporto** [comment]
I did some testing about the changes, so I believe it should not belong to this module. I guess it should be like a camera dock alternative.

Thank you for the feature request
