### ISSUE TITLE
Some useful icons on the video windows are missing (see screenshot)

### ISSUE THREAD

**Issue by franckflo** [patrickporto/avqol#4]
Using latest Foundry 10 (291) on Windows 10 in Opera Gx (Chromium), using the Forge Livekit server. 

First thanks for this very useful module allowing background images. Looking forward to future improvements :). 

When I enable A/V Quality of life, the Undock icon (left of each video) and sound off/on icon (right of each video) disappear, which prevents me from undocking the videos. See the screenshot below to see which icon I mean (screenshot was taken with A/V QoL disabled). 

![image](https://user-images.githubusercontent.com/80221412/221555948-c85b8f4e-7034-497f-8f91-9f7d2a8be716.png)

Thanks a bunch for looking into it!

**Comment by MythicalRollers** [comment]
There is a setting in the config for the module to turn things like undock on and off.  Do you have it check to show?

**Comment by franckflo** [comment]
I don't see any option about that in the Foundry A/V configuration window, nor the Likekit module nor the A/V QoL module. Could you elaborate where I can find them?

**Comment by patrickporto** [comment]
@franckflo check the settings
![image](https://user-images.githubusercontent.com/1543276/221636194-605ee8bb-aa16-4abe-b937-04a340bbbf1b.png)

If you use the voice button enhanced then the sound off/on will be hidden for now

**Comment by franckflo** [comment]
Found it, and that fixed it for me. Case closed, and many thanks!
