### ISSUE TITLE
Blur Effect

### ISSUE THREAD

**Issue by brunocalado** [patrickporto/avqol#5]
Hi. Great module.

Can you add a control to Blur? It's to weak

tks

**Comment by patrickporto** [comment]
Hi @brunocalado 

that's was added at https://github.com/patrickporto/avqol/releases/tag/1.0.0-alpha.4

**Comment by brunocalado** [comment]
> Hi @brunocalado
> 
> that's was added at https://github.com/patrickporto/avqol/releases/tag/1.0.0-alpha.4

Thank you!

How can manually trigger the interface? I can't find a way

**Comment by patrickporto** [comment]
![image](https://user-images.githubusercontent.com/1543276/221677760-423f1434-a18f-4a84-aecd-5535feccae05.png)

**Comment by brunocalado** [comment]
Thank you!
